# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20170726_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='image/default.png', max_length=200, null=True, upload_to='image/%Y/%m', verbose_name='\u6587\u7ae0\u7f29\u7565\u56fe'),
        ),
    ]
