# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='\u6587\u7ae0\u6807\u9898'),
        ),
    ]
